### ISSUE TITLE
multiple password prompts required with ssh remote

### ISSUE THREAD

**Issue by stephenhermes** [guildai/guildai#137]
When running training in the fashion mnist example on an ssh remote, I am prompted to enter my password five separate times:

```terminal
(guildtest) shermes:src shermes$ guild run fashion:train --remote some-remote
...
Initializing remote run
<prompt for password>
Copying package
<prompt for password>
building file list ... done
...
Installing package and its dependencies
<prompt for password>
Processing ./fashion-0.0.0-py2.py3-none-any.whl
...
Starting fashion:train on some-remote...
<prompt for password>
<prompt for password>
```
Similarly, I am getting five separate password prompts when running `guild pull some-remote`.

The multiple password issue with guild run happens in both 0.6.0 and 0.7.0rc8. (The issue with guild pull is only in 0.7.0rc8, but only because guild pull errors out in 0.6.0).

```yaml
// guild.yml
- model: fashion
  description: Simple classifier for Fashion-MNIST
  operations:
    train:
      description: Train classifier
      main: fashion_mnist

// ~/config.yml 
remotes:
  some-remote:
    type: ssh
    host: address-of-remote
    guild-env: ~/path/to/guild/venv
```
