### ISSUE TITLE
Run in remote: path notation

### ISSUE THREAD

**Issue by albertotb** [guildai/guildai#141]
A project with the following `guild.yml`

```
- model: test
  description: Train classifier
  operations:
    train:
      description: Train classifier
      main: ./src/train
```

runs fine locally, but returns the following error when trying to run in a remote:

```
WARNING: cannot import flags from ./src/train: No module named ./src/train
guild: No module named train
```

A possible workarround that works, suggested by @gar1t, is to convert `src` into a package by adding a `__init__.py` file inside `src` and replacing the config file by:

```
- model: test
  description: Train classifier
  operations:
    train:
      description: Train classifier
      main: src.train
```
