### ISSUE TITLE
Project level user config (was Conda-env per directory)

### ISSUE THREAD

**Issue by albertotb** [guildai/guildai#142]
Right now to run a script in a remote inside a conda environment we need a `~/.guild/config.yml` similar to this one:

```
remotes:
    my_remote:
        type: ssh
        host: my.remote
        conda-env: my_env
```

To run another script in a different environment, even in the same remote, we need to add another one. However, it is very common to have a setup with 1 environment per project, so it would be helpful being able to specify the `conda-env` configuration inside the local `guild.yml` file.

Another nice feature is for `guild` to automatically create the environment in the remote if the directory contains also an `env.yml` file (although I would say this is less useful)
