### ISSUE TITLE
Error:  unrecognized command 'test'

### ISSUE THREAD

**Issue by NiccoBiondi** [guildai/guildai#157]
Hi, 

I have installed guild 0.6.6 and I want to test my two models. My `guild.yml` has the following structure:

```yaml
- model: md1
  operations:
    train:
      main: foo1.py
      flags:
         f1:
            default: 2
         f2:
            default: 5

- model: md2
  operations:
    train:
      main: foo2.py
      flags:
         f1:
            default: 2
         f2:
            default: 5
```

From the [web page](https://guild.ai/docs/reference/guild-file/#tests), I read that I can write in the same file:

```yaml
- test: test models
  steps:
    - for-each-model:
        steps:
          - run: train f1=5 f2=[8,7,3]
          - run: train f1=[13,14,16] f2=10
```
for running the function **train** on both md1 and md2, with the command
`guild test`

This raises the following error:
```yaml
guild: unrecognized command 'test'
```

**Comment by gar1t** [comment]
Sorry about the long delay. Those docs of sadly out of date! The `test` mechanism has been migrated (mostly) into operations. The part that wasn't migrated is `for-each-model` - that's no longer supported.

This is how you would implement a stepped operation for your code:

```
- operations:
    test-models:
      steps:
        - m1:train f1=5 f2=[8,7,3]
        - m1:train f1=[13,14,16] f2=10
        - m2:train f1=5 f2=[8,7,3]
        - m2:train f1=[13,14,16] f2=10
```

I'll fix those docs - sorry about the confusion!
