### ISSUE TITLE
"argparse append action" like feature for non-fixed number of dependees

### ISSUE THREAD

**Issue by wheatdog** [guildai/guildai#162]
One type of operation I want to capture is data analysis and visualization. However I found that it is hard for guild to capture this kind of operations.

The number of runs that need to be analyzed are often not fixed, and it would be tedious to update the resources and requires in guild.yml every time. To solve this, guild can provide an "argparse append action" like feature to link non-fixed number of operation dependencies to a subfolder.

Here is an example,

# Example syntax 

Define `guild.yml` as follow. Notice that elements in `requires` have a key `mode` to enable `append` mode.
```yaml
# guild.yml

- model: my_model
  operations:
      test:
          main: test
      plot:
          main: plot
          requires:
              - name: test_output
                mode: append
  resources:
      test_output:
          sources:
              - operation: test
                select:
                    - score.txt
```

Then, one can run following command with as many as `test_output` as they need.
```
guild run my_model:plot test_output=hash1 test_output=hash2
```

Inside guild home, you can see the resources have been grouped under `test_output` with their hash values as subfolders.
```
.
├── hash1
│   └── score.txt
├── hash2
│   └── score.txt
└── plot_run_hash
    └── test_output
        ├── hash1
        │   └── score.txt -> ../../../hash1/score.txt
        └── hash2
            └── score.txt -> ../../../hash2/score.txt
```
