### ISSUE TITLE
exclude sourcecode not working

### ISSUE THREAD

**Issue by CarloLucibello** [guildai/guildai#177]
Configuring the `guild.yml` file to execute a `scripts/dnn.py` as follows
```yaml
train:
  main: scripts/dnn   
```
works fine, but when I add 
```yaml
train:
  main: scripts/dnn
  sourcecode: no
```
I get the following error
```bash
$ guild run train
Refreshing flags...
You are about to run train
Continue? (Y/n)
guild: No module named dnn
```
Same error with 
```yaml
train:
  main: scripts/dnn   
  sourcecode:
     - exclude: "*"
```

**Comment by gar1t** [comment]
Guild uses the source code to run your program. If you exclude the source code, the modules won't be around in the run directory to run.

You'd need to provide those modules some other way - e.g. either as file dependencies or by installing them in the environment.

**Comment by CarloLucibello** [comment]
Ok. Maybe you could consider removing the source files after the run when   
```
sourcecode: no
```
 so that the option is of larger use: e.g. when one has to perform many simulations and prefers to spare memory sacrificing reproducibility

**Comment by gar1t** [comment]
In that case what you can do is set `PYTHONPATH` to your project location to ensure that your project source is available.

```
your-operation:
  sourcecode: no
  env:
    PYTHONPATH: <path to your Python modules>
```

Just out of curiosity, how much disk space are you saving in this case? I'm wondering because perhaps there are some files that don't need to be copied over that you can filter out using an `exclude` rule.
