### ISSUE TITLE
Pipeline op can't find batch trials when resolving op dependencies

### ISSUE THREAD

**Issue by bharathc346** [guildai/guildai#196]
## Example 
```
operation_1: # has no dependencies

operation_2: 
    requires:
        - operation: operation_1
    flags-dest: globals
    flags-import:
        - some_param

operation_3: 
    requires:
        - operation: operation_2
    flags-dest: globals
    flags-import:
        - some_other_param

pipeline:
  steps:
    - run: operation_1
    - run: operation_2
      flags:
        some_param: [a, b]
    - run: operation_3
      flags:
        some_other_param: [1, 2, 3]
```

Running `guild run pipeline`

### Current Behavior 
`WARNING: cannot find a suitable run for required resource operation_1`
leads to 

`guild: run failed because a dependency was not met`

### Wanted Behavior
6 runs for operation_3 resembling batch trials (a1, a2, a3, b1, b2, b3, c1, c2, c3)
