### ISSUE TITLE
Support for argument group with argparse

### ISSUE THREAD

**Issue by fury00812** [guildai/guildai#200]
It would be great to add support for `argument_group` as follows:

```python
parser = argparse.ArgumentParser()
group = parser.add_argument_group("Data")
parser.add_argument("—src", default="")
```

```yml
train:
  main: src/main
  flags-dest: args
    flags:
      src: "train.txt"
```
