### ISSUE TITLE
Logspace via configuration file

### ISSUE THREAD

**Issue by radkoff** [guildai/guildai#222]
Hello,
I'm using a configuration file to specify appropriate search spaces for an optimizer. Something like this:
```
foo:
  main: foo
  flags-dest: args    # via ArgumentParser
  flags-import: all
  flags:
    bar: True
    weight: logspace[-2:2:5:2]   # [0.25, 0.5, 1.0, 2.0, 4.0]
```

However `guild run foo -o random` gets me:
```
ERROR: [guild] unknown function 'logspace' used for flag weight
```

I am able to use `loguniform[0.25, 4.0]` so it's not a big deal, but is this a bug?
