### ISSUE TITLE
Support for flag list values

### ISSUE THREAD

**Issue by gar1t** [guildai/guildai#226]
List values in Guild drive new experiments. E.g. `guild run lr=[0.01,0.1]` causes Guild to generate two runs, one for each specified value. What if the user wants to run one time with a single list value?

To do this today, user code must parse a string value. The command would be something like `guild run lr=0.01,0.1` (no square brackets). The user code would split the single value along this line:

``` python
lr = [float(x) for x in lr.split(",")]
```

This is not ideal. It requires code change. It fails poorly if the user accidentally types a non-float string.

Guild should support flag configuration indicating a value is a list. Guild should handle parsing, type coercion/validation, and error handling. This should work with Python globals, argparse, Click, and non-Python command line interfaces. (Note there's a hidden requirement here for flag config that specifies how the args are provided for a command - e.g. `--lr 0.01 --lr 0.1` vs `--lr 0.01 0.1`).

See https://my.guild.ai/t/how-do-i-use-variadic-args/293/2 "Implementation Notes" for more info.

cc @jethrokuan

**Comment by gar1t** [comment]
This is now available in Guild 0.7.2. The support is implemented using a new `arg-split` attribute, which indicates that a string flag value should be split into a list of values.

```
# guild.yml
op:
  flags:
    list-val:
      arg-name: l
      arg-split: yes
```

``` python
# op.py

l = [1, 2, 3]
print(l)
```

``` shell
$ guild run op list-val="4 5 6" -y
[4, 5, 6]
```

The value for `arg-split` can be one of: `yes` (alias for `shlex`, `no`, `shlex`, or a regular expression used to split the string. E.g. you can use a comma to split a comma-delimited list into parts.

Note that the flag value is specified by the user as an encoded string. The decoded value is a list based on the split spec.

**Comment by vitalwarley** [comment]
@gar1t, hello!

I am having problems with `arg-split` and [exec](https://my.guild.ai/t/operations/170#other-language-operations-5). I didn't create a new issue because this one is already (and yet?) open. 

Here is an MRE:

_guild.yml_

```yaml
- config: train-flags-finetune
  flags:
    lr-steps:
      arg-split: yes
      type: int

- model: tcc
  sourcecode: 
    - '*.py'
  operations:
    finetune:
      exec: torchrun --nnodes=1 --nproc_per_node=${nprocs} train.py --lr-steps=${lr-steps} 
      flags:
        $include: train-flags-finetune
        devices: 2
        nprocs: 2
      requires:
        - file: train.py
    
```

_train.py_

```python
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument(
    "--lr-steps",
    type=int,
    nargs="+",
)
args = parser.parse_args()

print(args)
```

Then I got

```
╚═╡(research) [17:50] λ guild run tcc:finetune lr-steps="10 10 10"
You are about to run tcc:finetune
  devices: 2
  lr-steps: 10 10 10
  nprocs: 2
Continue? (Y/n) 
Resolving file:train.py dependency
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
usage: train.py [-h] [--lr-steps LR_STEPS [LR_STEPS ...]]
train.py: error: argument --lr-steps: invalid int value: '10 10 10'
usage: train.py [-h] [--lr-steps LR_STEPS [LR_STEPS ...]]
train.py: error: argument --lr-steps: invalid int value: '10 10 10'
```

but if we change `finetune` op to

```yaml
    finetune:
      main: train
      flags:
        $include: train-flags-finetune
      requires:
        - file: train.py
```

the problem disappears

```
╚═╡(research) [17:56] λ guild run tcc:finetune lr-steps="10 10 10"
You are about to run tcc:finetune
  lr-steps: 10 10 10
Continue? (Y/n) 
Resolving file:train.py dependency
Namespace(lr_steps=[10, 10, 10])
```

Let me know if you need more info. Thanks!

---

```
guild_version:             0.8.1
guild_install_location:    /home/warley/.virtualenvs/research/lib/python3.9/site-packages/guild
guild_home:                /home/warley/.virtualenvs/research/.guild
guild_resource_cache:      /home/warley/.virtualenvs/research/.guild/cache/resources
installed_plugins:         config_flags, cpu, dask, disk, dvc, exec_script, gpu, ipynb, keras, memory, perf, python_script, queue, skopt
python_version:            3.9.12 (main, Apr  1 2022, 12:16:35) [GCC 11.2.0]
python_exe:                /home/warley/.virtualenvs/research/bin/python
platform:                  Linux 5.16.11-xanmod0-rog-1 x86_64
psutil_version:            5.9.0
tensorboard_version:       2.8.0
cuda_version:              11.7.64
nvidia_smi_version:        515.48.07
latest_guild_version:      0.8.1
```
