### ISSUE TITLE
References wrong run with choices parameters

### ISSUE THREAD

**Issue by joshy** [guildai/guildai#236]
Hi, maybe I am doing something wrong but in my settings it is referencing the wrong run when running test on some trained models with several choices.

In my `guild.yml` I have some flags like below for train and test:
```
flags:
  flag1:
    choices:["a", "b"]
  flag2:
    choices: ["x", "y"]
```
I run train with `guild run foo:train flag1="[a, b]" flag2="[x, y]"` and it will correctly start 4 runs (one for each combination). But when I run test with `guild run foo:test flag1="[a, b]" flag2="[x, y]"` it references always the last train run for each combination I want to test. 

I am running guild version: guild 0.7.0.post1

Thanks for guild.ai and your help!

**Comment by gar1t** [comment]
If you want to automate the sequence of running train followed by test using a grid-search, you need to synchronize the train/test steps using `steps` in a separate operation.

Here's a simple example you can run to experiment with:

``` yaml
train:
  main: guild.pass
  flags:
    a: null
    b: null

test:
  main: guild.pass
  a: null
  b: null
  requires:
    - operation: train

train-test:
  flags:
    a: null
    b: null
  steps:
    - train a=${a} b=${b}
    - test a=${a} b=${b}
```

To run four sets of trials for a set of flag values for a and b using something like:

```
$ guild run train-test a=[1,2] b=[3,4]
```

This will start a batch named `train-test+` which will run four `train-test` operations. Each `train-test` will run `train` followed by `test` using the applicable flag values.

You can delete these extra runs by running:

```
$ guild runs rm -o train-test
```

The scheme used here becomes quite painful when you have a lot of flags to define - as of 0.7 you have to duplicate them in the pipeline operation (i.e. `train-test`) and explicitly pass them through to the step operations. We're working on simplifying this to avoid this extra config. But for now you will have to duplicate at least the flag names for the pipeline ops.

**Comment by joshy** [comment]
Thanks a lot for your fast response. I have created a new operation but it cannot resolve the required operation from the train step. 

```yml
prepare:
  main: guild.pass
train:
  main: guild.pass
  requires:
    - operation: prepare
  flags:
    a: null
    b: null
test:
  main: guild.pass
  requires:
    - operation: prepare
    - operation: train
  flags:
    a: null
    b: null
train-test:
  # tried also without requires
  requires: 
    - operation: prepare
  flags:
    a: null
    b: null
  steps:
    - train a=${a} b=${b}
    - test a=${a} b=${b}
```
Running `foo:prepare` runs fine
Running `foo:train a=1 b=3` runs fine
Running `foo:train-test a=1 b=3` complains it cannot find required resource `prepare`

Full message:
```
You are about to run foo:train-test
  a: 1
  prepare: 5240ad11686e4e6783ca4313abaad95c
  b: 3
Continue? (Y/n)
Resolving prepare dependency
Using run 5240ad11686e4e6783ca4313abaad95c for prepare resource
INFO: [guild] running train: foo:train a=1 b=3
WARNING: cannot find a suitable run for required resource 'prepare'
Resolving prepare dependency
guild: run failed because a dependency was not met: could not resolve 'operation:prepare' in prepare resource: no suitable run for prepare
```
It finds the `prepare` run but somehow it is lost when it starts `train`.
