### ISSUE TITLE
File dependency not packaged for remote run

### ISSUE THREAD

**Issue by ghwatson** [guildai/guildai#279]
I get unexpected behaviour with the following simple file layout:

```
-prep_data.py
-patch.csv
-guild.yml
```

where the guild.yml contains:

```
prep_data:
  description: Prepare training + validation data. Has curation capabilities.
  main: prep_data
  requires:
    - file: patch.csv
      target-type: copy
  flags-dest: globals
  flags-import: all
```

Running `guild run prep_data` locally works fine, so I'm assuming in that case it maps the file `patch.csv` into the run directory. However, `guild run prep_data --remote myremote` does not work giving this error:

```
guild: run failed because a dependency was not met: could not resolve 'file:patch.csv' in file:patch.csv resource: cannot find source file 'patch.csv'
```

Looking through the output of that guild run command, it looks like patch.csv does not get packaged into the gpkg file for remote deployment.

Apologies in advance if I am just misinterpreting how to utilize file dependencies!

Some additional information: running `guild ls --sourcecode` turns up that csv file in the output list.
