### ISSUE TITLE
Flags not being imported from config files

### ISSUE THREAD

**Issue by gar1t** [guildai/guildai#308]
This issue is copied from a post to my.guild.ai.

I have the following guild yaml structure:

```
prepare-config:
    main: model.utils.prepare-config
    sourcecode: 
        root: /home/
        dest: .
        select: '*.py'

train:
    main: model.utils.run
    sourcecode: 
        root: /home/
        dest: .
        select: '*.py'
    requires:
      - operation: prepare-config
        select: prepare-config-output.json
        target-type: copy
        target-path: .
    flags-dest: config:prepare-config-output.json
    flags-import: all
```

In the run directory for the "train" operation I can see that the "prepare-config-output.json" file has been copied successfully. However when I perform "guild run train --help-op" I don't see any of the parameters in "prepare-config-output.json". I am even able to run "guild run train" successfully using the parameters in "prepare-config-output.json", but it seems as though the flags are not imported and I cant use something like "guild run train.py lr=[0.1, 0.01, 0.001]" for example.
