### ISSUE TITLE
flags-import matches partial arguments

### ISSUE THREAD

**Issue by AndrewPaulChester** [guildai/guildai#31]
When importing guild flags using the flags-import directive in the guild.yml file, any arguments defined by argparse which are substrings of the specified flags are also imported. See minimal working example below:

```
import argparse

parser = argparse.ArgumentParser(description="RL")
parser.add_argument("--import", default="test_file", help="import file")
parser.add_argument("--port", default="sydney", help="port of origin")
parser.add_argument("--not-imported", default="a2c", help="for demonstration")

parser.parse_args()
```

```
- model: argstest
  operations:
    train:
      main: guild_flag_test
      flags-import: 
        -import
```

running `guild run argstest:train`
gives the following output (port flag unexpected): 
```
You are about to run argstest:train
  import: test_file
  port: sydney
Continue? (Y/n) n
```
