### ISSUE TITLE
Unable to specify flags-import: all with remote runs

### ISSUE THREAD

**Issue by gar1t** [guildai/guildai#318]
Copied from https://my.guild.ai/t/unable-to-specify-flags-import-all-with-remote-runs/749

I have an operation in that looks like this
```
  operations:
    prepare:
      main: operations.prepare
      flags-import: all
      output-scalars: off
```
which has a number of different flags specified with argparse in `operations/prepare.py`. I can run it just fine locally, but when I try run it remote with any flag set I get `guild: unsupported flag <flag>` for every flag. I can run it remote as long as I don't set flags. Also, if I specify the flags explicitly in `guild.yml` like this it works fine:
```
    prepare:
      main: operations.prepare
      flags:
        <flag1>:
        <flag2>:
      output-scalars: off
```
Any idea what might be wrong here?
