### ISSUE TITLE
Sourcecode snapshots not selecting specified files

### ISSUE THREAD

**Issue by AndrewPaulChester** [guildai/guildai#39]
I can't get the new sourcecode root directory feature working as expected in my guild file. The below settings result in no sourcecode directory being captured at all, but removing the exclude line results in all files under the root directory being included. I have also tried using full rather than relative paths for the include statements with no success.
```
- model: ikostrikov
  ...
  sourcecode:
    root: '/home/achester/Documents'
    select:
        - exclude: '*'
        - include: '/home/achester/Documents/DRL/*.py'
        - include: 'domains/gym_taxi/*.py'
        - include: 'symbolic-goal-generation/*.py'
        - include: 'symbolic-goal-generation/planning/taxi/*.pddl'
        - include: symbolic-goal-generation/guild.yml
```
