### ISSUE TITLE
Use git (or other VCS) to determine source code files

### ISSUE THREAD

**Issue by gar1t** [guildai/guildai#410]
Unless a `sourcecode` spec is provided for an operation, Guild should first look for a local VCS repo and use that to infer source code for a project.

Guild should support a `sourcecode` directive that makes this config explicit (and use this by default). E.g.

``` yaml
op:
  sourcecode:
    - vcs-if-exists  # useful only as Guild-internal default
    # other specs here, to be applied ONLY if VCS does not exist

op-2
  sourcecode:
    - vcs  # nothing applied if VCS doesn't exist
    # rules here are always applied
``` 

Source code files need not be committed for this to work. Guild would get it's list of files by recursively iterating/selecting files not ignored (e.g. those showing up in `git status --ignored`)
