### ISSUE TITLE
`fail-if-empty` not used in run/operation resolution

### ISSUE THREAD

**Issue by gar1t** [guildai/guildai#430]
See https://my.guild.ai/t/self-requiring-operation/886

This should work:

``` yaml
op:
  requires:
    - operation: op
      fail-if-empty: no
```
