### ISSUE TITLE
Optional dependencies

### ISSUE THREAD

**Issue by gar1t** [guildai/guildai#431]
Support something like this:

``` yaml
op:
  requires:
    - operation: upstream
      optional: yes
```

Optional here might support a few different settings:

- `yes` - consider a missing source a normal case and print a message
- `'warn-if-missing'` - consider a missing source an abnormal case and print a warning message, but continue
- `'user-specified'` - require the resource if specified by the user for a run (e.g. `guild run <resource>=<location/id>`) otherwise treat as `yes` (optional, normal case)
