### ISSUE TITLE
Show required operations in --help-op and autocomplete.

### ISSUE THREAD

**Issue by copaah** [guildai/guildai#432]
When an operation requires another operation like this:

```
- model: model
  operations:
    train:
      main my_script
      flags:
        my_flag: 2
      requires:
        - operation: my_other_operation
```

You can do this in guild `guild run model:train my_other_operation=<RUN_ID>`. However, when you do `guild run model:train --help-op` only the flags are listed and provided with helpful information. ideally the required operation also would be printed. This goes for the auto-complete functionality as well.
