### ISSUE TITLE
New attr for operation that can be used for prompt labels

### ISSUE THREAD

**Issue by gar1t** [guildai/guildai#488]
Driver: `skopt:gp` is a cryptic way to spell "gaussian optimizer", as in this prompt:

```
$ guild run train.py --optimizer gaussian x=[-2.0:2.0]
You are about to run train.py with skopt:gp optimizer (20 trials, minimize loss)
...
```

Guild is deciding to short "<op name> optimizer" in the prompt. It might be nice to let the operation specify this so we could provide a more helpful prompt. E.g.

``` yaml
skopt:
  operations:
    gp:
      prompt-label: 'gaussian (skopt:gp) optimizer'
```

Or something along that line.

This would likely be applied for user runs as well.

E.g. a training operation:

```
train:
  prompt-label: "the world's best training algorithm (train)"
```
