### ISSUE TITLE
Guild doesn't resolve flag values in resource source select specs

### ISSUE THREAD

**Issue by gar1t** [guildai/guildai#499]
``` yaml
prep:
  flags:
    name: 01.npy
  requires:
    - file: data
      select: ${name}
```

For structure:

```
./guild.yml
./data/01.npy
``

Guild should select the file `01.npy` by default. It doesn't, I believe because it's not applying the flag value for `name` to the select spec before using it.
