### ISSUE TITLE
Confirm docs for supporting pre-0.9 guild home behavior

### ISSUE THREAD

**Issue by gar1t** [guildai/guildai#503]
Specifically, this:

``` yaml
# ~/.guild/config.yml
legacy:
  guild-home: pre-0.9
```
