### ISSUE TITLE
Filter runs by grid search

### ISSUE THREAD

**Issue by brunorigal** [guildai/guildai#520]
Hi, 
Thanks for this nice project!

I am running some grid search with the following `guild.yml`:
```
grid_search_main_script:
  description: Sample training script
  main: main_script

  flags:
    first_par: [0.2,0.4,0.6,1.]
    second_par: [10,100,1000,10000]
```

And I would like to retrieve all runs comming from one single grid search, which would require a label common to these runs (like a grid search time stamp). Is there a way to do this other than rewriting the grid search with the python API?
