### ISSUE TITLE
Warning on the YAML flags with `type: boolean`

### ISSUE THREAD

**Issue by merybenavente** [guildai/guildai#56]
Example of an operation:
```
operation:
  train:
    flags:
      generate_pos:
          type: boolean
          default: false
          choices: [true, false]
```
Warning output: `WARNING: unknown flag type 'boolean' for generate_pos - cannot coerce`.
