### ISSUE TITLE
Ignored files

### ISSUE THREAD

**Issue by PavloZakala** [guildai/guildai#66]
How to set list of ignored files?

**Comment by gar1t** [comment]
I assume this is for source code.

There are a couple options, both involve creating a Guild file with an operation and specifying a `sourcecode` attribute.

Option 1 - list your source code explicitly, thereby excluding everything else:

```
train:
  main: train
  sourcecode:
    - guild.yml
    - '*.py'
    - '*.txt'
```

Option 2, which uses the default logic but excludes specific paths (I believe this is what you're asking for):

```
train:
  main: train
  sourcecode:
    - exclude: '*.csv'
    - exclude: bigfile.txt
```

The operation name and main module `train` is just an example - use whatever makes sense for your application.
