### ISSUE TITLE
Support for subparsers and argument group with argparse

### ISSUE THREAD

**Issue by antoinebrl** [guildai/guildai#89]
Hello,
I'm trying to integrate guild into a project where the arguments are structured into groups with  argparse (`parser.add_argument_group(title="group1")`). Currently, the options inside the groups are not detected by guild. It would be nice to add support for argument group and subparsers.
Thanks a lot

**Comment by gar1t** [comment]
That's a good idea! This is a bit tricky as Guild would need the command in the `main` attr to know which subparser to read flags from. So you'd need to define the operation in a Guild file along these lines:

```
op:
  main: your_script some_command
```

where `some_command` is the command you want to target. Guild could then get the flags.

In the meantime, you can still explicitly define your flags in a Guild file for the operation. Each flag that you want to expose can be defined this way:

```
op:
  main: your_script some_command
  flags:
    flag_a:
      default: 123
      description: Some flag
    flag_b: ...
```
